version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - twitch-net

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - twitch-net
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: twitchdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - twitch-net

networks:
  twitch-net:
    external: true

volumes:
  db-data:










